### PR TITLE
Bump IntifaceCLI.exe to v50

### PR DESCRIPTION
**Pull request by hogefugamoga**
Hello, thank you for sharing awesome package.
It seems current IntifaceCLI.exe is too old (v36).
I want to use v39+ because I need Vorze Piston support.

https://github.com/intiface/intiface-cli-rs/blob/master/CHANGELOG.md

I thought I can just update my Assets/StreamingAssets directory to bump IntifaceCLI but it seems it's overwritten when I compile.
So I guess I need to update this package itself.
I'm new to Unity so please let me know if I'm wrong.

Thanks.

### CODE REVIEW

**Comment by hogefugamoga** [comment]
@qdot WDYT?

**Comment by qdot** [comment]
@hogefugamoga Agh, sorry, this is definitely something that needs to get done, I've just been busy trying to get the new library version and surrounding tech on that done so I can update everything at once. Hoping I'll have something on that soon. 

Once I've got the new apps out I'm probably going to do an overhaul of this plugin, as the way it works right now is... not great. I'll be moving the Unity portion to be pure C# again, and will be recommending people use Intiface Central (the new Intiface Desktop, but it'll ship on phones too) instead of embedding a process, though that'll still be available as a default. All of that work is going to take more time though, so I'll at least see about getting the executable updated here first.

**Comment by hogefugamoga** [comment]
@qdot It seems that buttplug-csharp had some updates but how about this package?

**Comment by qdot** [comment]
I'm tryin', just very very out of time to do much of anything right now. This package needs to be rebuilt on top of the new C# package, and I'm hoping to also write up documentation on game integration.

**Comment by qdot** [comment]
Updates are now happening in the v3 branch, but I'll warn that things look VERY different there now. Basically I've stripped buttplug-unity down to just being a repackage of the nuget DLLs from the C# project, with no Engine/CLI packaged here anymore. I know some developers are interested in doing that and I'm discussing how that'd work now, but in general I recommend just having users use Intiface Central.

**Pull request closed without merging**
